import { StyleSheet } from "react-native";
import { SCREEN_WIDTH } from "../../constants/dimensions";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#FAFAFA",
	},
	loadingContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	errorContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		padding: 20,
	},
	errorText: {
		fontSize: 18,
		color: "#666666",
		marginBottom: 20,
	},
	backButton: {
		backgroundColor: "#0066FF",
		paddingHorizontal: 20,
		paddingVertical: 10,
		borderRadius: 8,
	},
	backButtonText: {
		color: "#FFFFFF",
		fontSize: 16,
		fontWeight: "600",
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 16,
		paddingVertical: 12,
		backgroundColor: "#FFFFFF",
		borderBottomWidth: 1,
		borderBottomColor: "#E5E5E7",
	},
	headerButton: {
		padding: 4,
	},
	headerTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#000000",
		flex: 1,
		textAlign: "center",
	},
	headerActions: {
		flexDirection: "row",
		gap: 12,
	},
	content: {
		flex: 1,
	},
	imageContainer: {
		position: "relative",
		backgroundColor: "#FFFFFF",
		marginBottom: 16,
	},
	documentImage: {
		width: SCREEN_WIDTH,
		height: SCREEN_WIDTH * 0.75,
		backgroundColor: "#F2F2F7",
	},
	confidenceBadge: {
		position: "absolute",
		top: 16,
		right: 16,
		backgroundColor: "rgba(0, 102, 255, 0.9)",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 16,
	},
	confidenceText: {
		color: "#FFFFFF",
		fontSize: 14,
		fontWeight: "600",
	},
	metadataContainer: {
		backgroundColor: "#FFFFFF",
		marginHorizontal: 16,
		padding: 16,
		borderRadius: 8,
		marginBottom: 16,
	},
	metadataHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 16,
	},
	metadataTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#000000",
	},
	metadataItem: {
		marginBottom: 16,
	},
	editButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
	},
	editButtonText: {
		color: "#0066FF",
		fontSize: 16,
		fontWeight: "500",
	},
	metadataRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingVertical: 8,
		borderBottomWidth: 1,
		borderBottomColor: "#F2F2F7",
	},
	metadataLabel: {
		fontSize: 14,
		color: "#666666",
		flex: 1,
	},
	metadataValue: {
		fontSize: 14,
		color: "#000000",
		flex: 2,
		textAlign: "right",
	},
	editInput: {
		flex: 2,
		borderWidth: 1,
		borderColor: "#E5E5E7",
		borderRadius: 6,
		paddingHorizontal: 8,
		paddingVertical: 4,
		fontSize: 14,
		textAlign: "right",
	},
	amountEditContainer: {
		flex: 2,
		flexDirection: "row",
		gap: 8,
	},
	currencyInput: {
		flex: 0.8,
	},
	amountInput: {
		flex: 1.2,
	},
	textSection: {
		backgroundColor: "#FFFFFF",
		marginHorizontal: 16,
		padding: 16,
		borderRadius: 8,
		marginBottom: 16,
	},
	sectionLabel: {
		fontSize: 18,
		fontWeight: "600",
		color: "#000000",
		marginBottom: 12,
	},
	textLine: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingVertical: 8,
		borderBottomWidth: 1,
		borderBottomColor: "#F2F2F7",
	},
	lineText: {
		fontSize: 14,
		color: "#333333",
		flex: 1,
		marginRight: 8,
	},
	fullMetadataButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#FFFFFF",
		marginHorizontal: 16,
		marginBottom: 32,
		padding: 16,
		borderRadius: 8,
		gap: 8,
	},
	fullMetadataButtonText: {
		color: "#0066FF",
		fontSize: 16,
		fontWeight: "500",
	},
	imagePlaceholder: {
		justifyContent: "center",
		alignItems: "center",
	},
	imagePlaceholderText: {
		color: "#999999",
		fontSize: 16,
		marginTop: 8,
	},
	showThumbnailButton: {
		marginTop: 16,
		paddingHorizontal: 16,
		paddingVertical: 8,
		backgroundColor: "#0066FF",
		borderRadius: 6,
	},
	showThumbnailButtonText: {
		color: "#FFFFFF",
		fontSize: 14,
		fontWeight: "500",
	},
	hybridSection: {
		backgroundColor: "#FFFFFF",
		marginHorizontal: 16,
		padding: 16,
		borderRadius: 8,
		marginBottom: 16,
	},
	hybridTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#000000",
		marginBottom: 16,
	},
	qualityContainer: {
		marginBottom: 16,
	},
	qualityTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#5856D6",
		marginBottom: 8,
	},
	metricsGrid: {
		flexDirection: "row",
		gap: 8,
		marginBottom: 12,
	},
	metricItem: {
		flex: 1,
		backgroundColor: "#F8F8FF",
		padding: 8,
		borderRadius: 6,
		alignItems: "center",
	},
	metricLabel: {
		fontSize: 11,
		color: "#666666",
		marginBottom: 2,
	},
	metricValue: {
		fontSize: 13,
		fontWeight: "600",
		color: "#5856D6",
	},
	warningsContainer: {
		backgroundColor: "#FFF3CD",
		padding: 8,
		borderRadius: 6,
		borderLeftWidth: 3,
		borderLeftColor: "#FFC107",
	},
	warningsTitle: {
		fontSize: 14,
		fontWeight: "600",
		color: "#856404",
		marginBottom: 4,
	},
	warningText: {
		fontSize: 12,
		color: "#856404",
		marginBottom: 2,
	},
	entitiesContainer: {
		marginBottom: 16,
	},
	entitiesTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#34C759",
		marginBottom: 8,
	},
	entitiesGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 6,
	},
	entityBadge: {
		backgroundColor: "#E8F5E8",
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 4,
		maxWidth: "48%",
	},
	entityType: {
		fontSize: 10,
		fontWeight: "600",
		color: "#2E7D32",
		textTransform: "uppercase",
	},
	entityValue: {
		fontSize: 11,
		color: "#2E7D32",
		marginTop: 2,
	},
	processingInfoContainer: {
		backgroundColor: "#F2F2F7",
		padding: 12,
		borderRadius: 6,
	},
	processingInfoTitle: {
		fontSize: 14,
		fontWeight: "600",
		color: "#000000",
		marginBottom: 8,
	},
	processingInfoRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 4,
	},
	processingInfoLabel: {
		fontSize: 12,
		color: "#666666",
	},
	processingInfoValue: {
		fontSize: 12,
		color: "#000000",
		fontWeight: "500",
	},
	documentTypeContainer: {
		marginBottom: 16,
	},
	sectionTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#000000",
		marginBottom: 8,
	},
	documentTypeBadge: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#F0F0F0",
		paddingVertical: 8,
		paddingHorizontal: 16,
		borderRadius: 8,
		alignSelf: "flex-start",
	},
	documentTypeText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#000000",
		textTransform: "capitalize",
	},
	totalScore: {
		color: "#0066FF",
	},
	structuredDataContainer: {
		marginBottom: 16,
	},
	dataRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		paddingVertical: 8,
		borderBottomWidth: 1,
		borderBottomColor: "#F0F0F0",
	},
	dataLabel: {
		fontSize: 14,
		color: "#666666",
	},
	dataValue: {
		fontSize: 14,
		fontWeight: "600",
		color: "#000000",
		flex: 1,
		textAlign: "right",
	},
	itemsContainer: {
		marginTop: 8,
		marginBottom: 8,
	},
	itemText: {
		fontSize: 14,
		color: "#333333",
		marginTop: 4,
		marginLeft: 16,
	},
	statsContainer: {
		paddingTop: 16,
		borderTopWidth: 1,
		borderTopColor: "#F0F0F0",
	},
	statsTitle: {
		fontSize: 14,
		fontWeight: "600",
		color: "#666666",
		marginBottom: 8,
	},
	statsText: {
		fontSize: 12,
		color: "#666666",
		marginBottom: 4,
	},
});
