# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

project 'Visara.xcodeproj'
platform :ios, '15.5'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Visara' do
  config = use_native_modules!

  # WatermelonDB dependencies
  pod 'simdjson', :path => '../node_modules/@nozbe/simdjson'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Enabling the New Architecture for React Native
    :fabric_enabled => true,
    :hermes_enabled => true
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Additional optimizations for performance and New Architecture
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable bitcode (deprecated in Xcode 14)
        config.build_settings['ENABLE_BITCODE'] = 'NO'

        # Set deployment target to iOS 15.5 minimum
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'

        # Optimize for speed
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 's'

        # Enable whole module optimization for Swift
        config.build_settings['SWIFT_WHOLE_MODULE_OPTIMIZATION'] = 'YES'

        # Dead code stripping
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'

        # Exclude architectures for simulator (keep only x86_64 and arm64)
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      end
    end
  end
end
